### ISSUE TITLE
Shadow Stack and Indirect Branch Tracking support

### ISSUE THREAD

**Issue by loqs** [libunwind/libunwind#644]
Would it be possible to add support for either of these features to libunwind [1]?

Compilers will generate code supporting these features when -fcf-protection option is used.  Assembly code needs to add a .note.gnu.property section specifying which features are supported which serves a similar function to .note.GNU-stack and is checked by the linker.  I do not believe any other changes would be needed for shadow stack support unless the library makes use of the stack.  Indirect branch tracking requires all indirect branch targets be marked with ENDBR.  You can see how support has been added to a number of projects at [2].  Shadow stack support has been merged into the kernel for 6.6 [3] and I expect compatible glibc support for it will be added once 6.6 is released.

[1]: https://www.intel.com/content/dam/develop/external/us/en/documents/catc17-introduction-intel-cet-844137.pdf
[2]: https://gitlab.com/cet-software
[3]: https://github.com/torvalds/linux/commit/df57721f9a63e8a1fb9b9b2e70de4aa4c7e0cd2e

**Comment by bregma** [comment]
These are really two separate issues.

Shadow stack support would affect anything that leverages `setcontext()` such as `longjmp()` and C++ exceptions and would require some unwinder customization.

IBT has even less effect and would only be relevant in adding another test case of trampoline/PLT/kernel call detection.

No objection to adding this functionality, patches are welcome.

**Comment by loqs** [comment]
@hjl-tools would this be of interest to you?

**Comment by eslerm** [comment]
Looks like this was resolved by @bregma 😎 https://github.com/libunwind/libunwind/pull/898

**Comment by loqs** [comment]
@eslerm it has been partially resolved; all the libraries apart from `libunwind-setjmp.so` are now built with shadow stack and indirect branch tracking enabled.
Steps I used to check the current git head b2d2e81e5fe53b01a0dd39e2e634f963ebeaab43:
```
$ git clone https://github.com/libunwind/libunwind.git
$ cd libunwind
$   git describe --tags
v1.8-branchpoint-126-gb2d2e81e
$ autoreconf -fiv
$ LDFLAGS='-Wl,-z,cet-report=error' CFLAGS='-fcf-protection' ./configure
$ make
....
/usr/bin/ld: x86_64/.libs/longjmp.o: error: missing IBT and SHSTK properties
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4110: libunwind-setjmp.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/build/libunwind/src/libunwind/src'
make[1]: *** [Makefile:2970: all] Error 2
make[1]: Leaving directory '/build/libunwind/src/libunwind/src'
make: *** [Makefile:631: all-recursive] Error 1
```
Full build output attached.
[libunwind-v1.8.branchpoint.r126.gb2d2e81-1-x86_64-build.log](https://github.com/user-attachments/files/21631399/libunwind-v1.8.branchpoint.r126.gb2d2e81-1-x86_64-build.log)

**Comment by hjl-tools** [comment]
> With [#901](https://github.com/libunwind/libunwind/pull/901) applied all libraries are built with shadow stack and indirect branch support apart from one test case (which is expected). However when shadow stack is enabled six tests failed:
> 
> ```
> ../config/test-driver: line 119: 17770 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> ../config/test-driver: line 119: 17798 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> FAIL: Gtest-exc
> FAIL: Ltest-resume-sig-rt
> SKIP: run-coredump-unwind
> ../config/test-driver: line 119: 17811 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> FAIL: Ltest-resume-sig
> SKIP: run-coredump-unwind-mdi
> ../config/test-driver: line 119: 17777 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> FAIL: Gtest-resume-sig
> ../config/test-driver: line 119: 17754 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> FAIL: Ltest-exc
> ../config/test-driver: line 119: 17812 Segmentation fault         (core dumped) "$@" >> "$log_file" 2>&1
> FAIL: Gtest-resume-sig-rt
> ```
>

It looks like that shadow stack isn't properly unwound.   Please build GDB with GDB shadow stack patch set from:

https://patchwork.sourceware.org/project/gdb/list/?series=49073

and run the failed tests under GDB with shadow stack support to find out why they fail.

> [test-suite.log](https://github.com/user-attachments/files/21689645/test-suite.log) [@hjl-tools](https://github.com/hjl-tools) any suggestions?
> 
> As the Linux kernel does not support indirect branch tracking for userspace at present and I lack hardware supporting it I was unable to test that.

**Comment by loqs** [comment]
```
$ LD_LIBRARY_PATH="/build/libunwind/src/libunwind/src/.libs:$LD_LIBRARY_PATH" gdb tests/.libs/Gtest-exc
...
(gdb) run
Starting program: /build/libunwind/src/libunwind/tests/.libs/Gtest-exc 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading 1.13 M separate debug info for /lib64/ld-linux-x86-64.so.2...
Downloading 9.88 M separate debug info for /usr/lib/libc.so.6...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading 889.26 K separate debug info for /usr/lib/liblzma.so.5...

Program received signal SIGSEGV, Segmentation fault.
_Ux86_64_setcontext () at x86_64/setcontext.S:86
⚠️ warning: 86	x86_64/setcontext.S: No such file or directory
(gdb) bt full
#0  _Ux86_64_setcontext () at x86_64/setcontext.S:86
No locals.
#1  0x00005555555554a4 in a (n=13) at /usr/src/debug/libunwind/libunwind/tests/Gtest-exc.c:118
        stack = 140737354070835
        result = 99
#2  0x0000555555555062 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/libunwind/libunwind/tests/Gtest-exc.c:168
        result = <optimized out>
```
Which points to https://github.com/libunwind/libunwind/blob/2ad7f439d6d04a808947e04b07e1efb34371c8b2/src/x86_64/setcontext.S#L86

**Comment by hjl-tools** [comment]
Please take a look at glibc setjmp/longjmp to learn how to unwind stack.
